# -*- coding: utf-8 -*- --------------------------------------------------===#
#
#  Copyright 2022 Trovares Inc.
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.
#
#===----------------------------------------------------------------------===#

name: PyTest
on:
  push:
    branches: [ main ]
    paths:
      - '.github/**'
      - 'src/**'
      - 'test/**'
  pull_request:
    branches: [ main ]
    paths:
      - '.github/**'
      - 'src/**'
      - 'test/**'
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 20
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.6', '3.7','3.8', '3.9', '3.10']

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # TODO(landwehrj) Workaround for backwards compatibility issues with protobuf
        pip install py2neo parameterized 'protobuf>=3.12.0,<=3.20.1'
        pip install -r requirements.txt
        pip install pytest
        pip install ./
        wget https://raw.githubusercontent.com/neo4j-field/neo4j-arrow/main/python/neo4j_arrow.py -P ./test

    - name: Launch neo4j
      run: |
        mkdir -p neo4j/plugins
        wget -O neo4j/plugins/neo4j-arrow-4.1-all.jar https://github.com/neo4j-field/neo4j-arrow/releases/download/v4.1/neo4j-arrow-4.1-all.jar
        docker run --rm -d --name neo4j -p7474:7474 -p7687:7687 -p 9999:9999 \
            --user=$(id -u):$(id -g) -v $PWD/neo4j/plugins:/var/lib/neo4j/plugins \
            --env NEO4J_AUTH=neo4j/foo --env NEO4J_EDITION=community \
            --env NEO4JLABS_PLUGINS='["graph-data-science"]' \
            --env HOST=0.0.0.0  --env NEO4J_dbms_default__listen__address=0.0.0.0 \
            neo4j:4.4.4

    - name: Launch xGT
      run: "docker run --rm -d --name xgt -p 4367:4367 trovares/xgt"

    - name: Show docker containers
      run: "docker ps -a"

    - name: Run test suite
      run: |
        pytest -v -s test
