# .github/workflows/pytest.yaml
name: PyTest
on:
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'test/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'test/**'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: ['3.6','3.7','3.8', '3.9', '3.10']

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: setup python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest
        pip install -e git+https://github.com/trovares/xgt_neo4j_connector.git#egg=xgt_neo4j_connector

    - name: Launch xGT
      run: "docker run --rm -d --name xgt -p 4367:4367 trovares/xgt"

    - name: Run test suite
      run: |
        pytest -v -s test
