name: Sphinx build

on:
  push:
    paths:
      - '.github/**'
      - 'src/**'
      - 'docs/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build HTML
      uses: ammaraskar/sphinx-action@0.4
      with:
        # TODO(landwehrj) Workaround for backwards compatibility issues with protobuf
         pre-build-command: "pip install 'protobuf>=3.12.0,<=3.20.1'"
    - name: Upload artifacts
      uses: actions/upload-artifact@v1
      with:
        name: html-docs
        path: docs/build/html/
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: docs/build/html
