jobs:
  pypi-test:
    timeout-minutes: 20
    runs-on: ubuntu-latest

    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        # TODO(landwehrj) Workaround for backwards compatibility issues with protobuf
        pip install 'protobuf>=3.12.0,<=3.20.1'
        pip install -r requirements.txt
        python -m build

    - name: Publish package to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        user: __token__
        password: ${{ secrets.TEST_PYPI_API_TOKEN }}
        repository_url: https://test.pypi.org/legacy/
